[package]
name = "accounts"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
db.workspace = true
domain.workspace = true
hmac.workspace = true
secrecy.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
