//! `SQLx` persistence for Pakperk.
//!
//! The crate maps database rows onto transport-agnostic `domain` values. Raw
//! row structs remain private so service code cannot accidentally couple to
//! SQL column layouts.

mod cursor;
mod repository;

pub use cursor::{
    CreatedAtCursor, CursorError, EncryptedReadingFeedCursorCodec, FeedCursor, LibraryCursor,
    READING_FEED_CURSOR_PURPOSE,
};
pub use repository::{
    AccountDeletionFailure, AccountDeletionRepository, AccountDeletionRequest,
    AccountDeletionRequestOutcome, AccountRepository, AdminCommentAction, AdminCommentOutcome,
    AdminReportOutcome, AdminReportResolution, AdminUserStatusOutcome, ArtifactPersistOutcome,
    AssistantContextRepository, AssistantEvidenceFeedbackOutcome, AssistantHistoryRole,
    AssistantMessage, AssistantRetentionCleanup, AssistantRetrievalContext, AssistantSession,
    AssistantThread, ChatSession, ClaimedAccountDeletion, ClaimedRecommendationGeneration,
    CommentCreateOutcome, CommentCreatePrecondition, CommentCreateResolution,
    CommentDeleteResolution, CommentEditResolution, CommentMutationOutcome, CommentReadOutcome,
    CommentReportOutcome, CommentReportResolution, CommentRepository, CommentWriteGuard,
    CurrentDocument, CurrentPassport, CurrentSemanticSpans, DOCUMENT_BLOCK_PAGE_DEFAULT,
    DOCUMENT_BLOCK_PAGE_MAX, Database, DbError, DeferredDiscoveryMetrics, DeletionLedgerRecord,
    DeletionReapplyAction, DeletionReapplyOutcome, DiscoverySearchRepository, DocumentBlockPage,
    DocumentBlockQuery, DocumentPersistOutcome, DocumentRepository, EngagementRepository,
    EnrichmentCapability, ExternalLedgerPurgeAuthorization, ExternalLedgerPurgeAuthorizationState,
    FeedQuery, FeedbackEvaluationOutcome, InteractionEventType, InteractionFeedMode,
    InteractionPrincipal, LibraryChangesOutcome, LibraryCollectionIntent, LibraryItemFilter,
    LibraryItemMutation, LibraryItemTagWrite, LibraryListItemWrite, LibraryListWrite,
    LibraryMutationIntent, LibraryMutationOutcome, LibraryOperationResolution, LibraryReadOutcome,
    LibraryRepository, LibraryTagWrite, LibraryV2MutationOutcome, LibraryV2ReadOutcome,
    MAX_INTERACTION_BATCH, ModerationRepository, ObservedAnnotationReanchor,
    PaperImportFinalization, PaperImportFinalizeOutcome, PaperImportFingerprint,
    PaperImportInputKind, PaperImportReadOutcome, PaperImportRepository, PaperImportReserveOutcome,
    PaperImportStatus, PaperInteractionBatchOutcome, PaperInteractionBatchRequest,
    PaperInteractionRepository, PaperInteractionRepositoryError, PaperInteractionWrite,
    PaperRepository, PassportRepository, PendingAnnotationReanchor, PrepareResult, ProfilePatch,
    ProfileUpdateOutcome, RateLimitConfigError, RateLimitDecision, RateLimitRepository,
    RateLimitRequest, ReadingFeedRepository, RecommendationBatchBlockOutcome,
    RecommendationBatchBlockRequest, RecommendationBatchPersistOutcome,
    RecommendationBatchPersistRequest, RecommendationBatchRepository,
    RecommendationBatchRepositoryError, RecommendationBatchServeOutcome,
    RecommendationBatchServeRequest, RecommendationExplanationReadOutcome,
    RecommendationFeedbackContext, RecommendationFeedbackOutcome, RecommendationFeedbackReason,
    RecommendationFeedbackType, RecommendationFeedbackWrite, RecommendationGenerationCleanup,
    RecommendationGenerationEnqueue, RecommendationGenerationEnqueueOutcome,
    RecommendationGenerationJobState, RecommendationGenerationRepository,
    RecommendationGenerationRepositoryError, RecommendationGenerationRetryOutcome,
    RecommendationRetentionCleanup, ResearchAnnotationImport, ResearchAnnotationImportOutcome,
    ResearchAnnotationImportResult, ResearchArtifactExport, ResearchArtifactExportPage,
    ResearchExportAssistantEvidenceFeedback, ResearchExportAssistantMessage,
    ResearchExportAssistantThread, ResearchExportLibraryItem, ResearchExportManifest,
    ResearchExportManifestPaper, ResearchExportPaper, ResearchExportPrivateProvenance,
    ResearchMemoryRepository, ResearchMutationOutcome, ResearchProfileRepository,
    ResearchReadOutcome, RetrievalCandidate, RetrievedAssistantBlock,
    SavedSearchRecommendationContext, StoredAccountDeletionBacklogMetrics,
    StoredAccountDeletionStatus, StoredAdminActor, StoredAnnotationConflict,
    StoredAnnotationConflictPage, StoredAnnotationPage, StoredCheckpoints,
    StoredDeletionIdentityVerification, StoredEvidenceCardPage, StoredInspectionReport,
    StoredLibraryChangesPage, StoredLibraryLists, StoredLibraryPage, StoredLibraryTags,
    StoredLibraryV2ChangesPage, StoredMemoryPage, StoredModerationInspection,
    StoredModerationQueuePage, StoredModerationQueueRecord, StoredPaperImportOperation,
    StoredReanchorAttempt, StoredRecommendationBatchStatus, StoredRecommendationCandidate,
    StoredReport, StoredReportAgeMetrics, StoredReportQueuePage, StoredReportQueueRecord,
    StoredSection, StoredUserReport, StoredUserReportInspection, StoredUserReportQueuePage,
    StoredUserReportQueueRecord, TitleCandidate, UserBlockOutcome, UserBlockResolution,
    UserReportOutcome, UserReportResolution, UserUnblockResolution, VerificationMetrics,
    VersionDiffRepository, VersionDiffSourceSide, VersionDiffSourceTarget, VisualObjectReference,
};
