import 'package:flutter/material.dart';

abstract final class PakPerkTypography {
  static TextTheme textTheme(ColorScheme colors) => TextTheme(
    displayLarge: TextStyle(
      color: colors.onSurface,
      fontSize: 40,
      height: 1.04,
      fontWeight: FontWeight.w700,
      letterSpacing: -1.1,
    ),
    displayMedium: TextStyle(
      color: colors.onSurface,
      fontSize: 36,
      height: 1.06,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.9,
    ),
    displaySmall: TextStyle(
      color: colors.onSurface,
      fontSize: 34,
      height: 1.08,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.7,
    ),
    headlineLarge: TextStyle(
      color: colors.onSurface,
      fontSize: 28,
      height: 1.12,
      fontWeight: FontWeight.w600,
      letterSpacing: -0.45,
    ),
    headlineMedium: TextStyle(
      color: colors.onSurface,
      fontSize: 26,
      height: 1.14,
      fontWeight: FontWeight.w600,
      letterSpacing: -0.35,
    ),
    headlineSmall: TextStyle(
      color: colors.onSurface,
      fontSize: 24,
      height: 1.18,
      fontWeight: FontWeight.w600,
      letterSpacing: -0.3,
    ),
    titleLarge: TextStyle(
      color: colors.onSurface,
      fontSize: 20,
      height: 1.22,
      fontWeight: FontWeight.w600,
      letterSpacing: -0.15,
    ),
    titleMedium: TextStyle(
      color: colors.onSurface,
      fontSize: 17,
      height: 1.28,
      fontWeight: FontWeight.w600,
      letterSpacing: -0.05,
    ),
    titleSmall: TextStyle(
      color: colors.onSurface,
      fontSize: 15,
      height: 1.32,
      fontWeight: FontWeight.w600,
      letterSpacing: 0,
    ),
    bodyLarge: TextStyle(
      color: colors.onSurface,
      fontSize: 17,
      height: 1.5,
      fontWeight: FontWeight.w400,
      letterSpacing: 0,
    ),
    bodyMedium: TextStyle(
      color: colors.onSurface,
      fontSize: 15,
      height: 1.43,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.05,
    ),
    bodySmall: TextStyle(
      color: colors.onSurfaceVariant,
      fontSize: 13,
      height: 1.4,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.1,
    ),
    labelLarge: TextStyle(
      color: colors.onSurface,
      fontSize: 15,
      height: 1.24,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.05,
    ),
    labelMedium: TextStyle(
      color: colors.onSurfaceVariant,
      fontSize: 13,
      height: 1.3,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.15,
    ),
    labelSmall: TextStyle(
      color: colors.onSurfaceVariant,
      fontSize: 12,
      height: 1.32,
      fontWeight: FontWeight.w700,
      letterSpacing: 0.55,
    ),
  );
}
