#!/usr/bin/env python3
"""Tamper regressions for Gradle artifact verification metadata."""

from __future__ import annotations

import pathlib
import tempfile
import unittest

import validate_gradle_verification as validator


class GradleVerificationTests(unittest.TestCase):
    def test_checked_in_policy_passes(self) -> None:
        validator.validate(validator.DEFAULT_METADATA)

    def test_reviewed_checksum_tamper_fails(self) -> None:
        source = validator.DEFAULT_METADATA.read_text(encoding="utf-8")
        expected = validator.REQUIRED_ARTIFACTS[
            ("net.openid", "appauth", "0.11.1", "appauth-0.11.1.aar")
        ]
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "verification-metadata.xml"
            path.write_text(source.replace(expected, "0" * 64, 1), encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "reviewed Gradle artifact changed"):
                validator.validate(path)

    def test_linux_build_tool_removal_fails(self) -> None:
        source = validator.DEFAULT_METADATA.read_text(encoding="utf-8")
        marker = (
            '         <artifact name="aapt2-9.0.1-14304508-linux.jar">\n'
            '            <sha256 value="ab04484e27480404a32df818c1da12bebaceadab4895f50880153dfaad84e748" origin="Verified from Google Maven for Linux CI"/>\n'
            "         </artifact>\n"
        )
        self.assertIn(marker, source)
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "verification-metadata.xml"
            path.write_text(source.replace(marker, "", 1), encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "reviewed Gradle artifact changed"):
                validator.validate(path)

    def test_trusted_artifact_bypass_fails(self) -> None:
        source = validator.DEFAULT_METADATA.read_text(encoding="utf-8")
        marker = "      <verify-signatures>false</verify-signatures>\n"
        self.assertIn(marker, source)
        bypass = (
            marker
            + "      <trusted-artifacts>\n"
            + '         <trust group=".*" name=".*" version=".*"/>\n'
            + "      </trusted-artifacts>\n"
        )
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "verification-metadata.xml"
            path.write_text(source.replace(marker, bypass, 1), encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "without trust exceptions"):
                validator.validate(path)

    def test_alternate_checksum_bypass_fails(self) -> None:
        source = validator.DEFAULT_METADATA.read_text(encoding="utf-8")
        marker = (
            '            <sha256 value="d9ff43b14f7ee8e81bc802148190ad808beb5389953e6e6ffa53cd5575ea611e" '
            'origin="Generated by Gradle"/>\n'
        )
        self.assertIn(marker, source)
        bypass = marker + f'            <sha512 value="{"0" * 128}"/>\n'
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "verification-metadata.xml"
            path.write_text(source.replace(marker, bypass, 1), encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "exactly one SHA-256"):
                validator.validate(path)

    def test_artifact_bypass_attribute_fails(self) -> None:
        source = validator.DEFAULT_METADATA.read_text(encoding="utf-8").replace(
            '<artifact name="appauth-0.11.1.aar">',
            '<artifact name="appauth-0.11.1.aar" trusted="true">',
            1,
        )
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "verification-metadata.xml"
            path.write_text(source, encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "unsupported verification attributes"):
                validator.validate(path)

    def test_signature_mode_drift_fails(self) -> None:
        source = validator.DEFAULT_METADATA.read_text(encoding="utf-8").replace(
            "<verify-signatures>false</verify-signatures>",
            "<verify-signatures>true</verify-signatures>",
            1,
        )
        with tempfile.TemporaryDirectory() as directory:
            path = pathlib.Path(directory) / "verification-metadata.xml"
            path.write_text(source, encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "without trust exceptions"):
                validator.validate(path)


if __name__ == "__main__":
    unittest.main()
