import { execFileSync } from "node:child_process";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "../..");
const sourceRoot = path.join(root, "docs");
const translatedRoot = path.join(root, "docs-site", "content", "zh");
const generatedPath = path.join(root, "docs-site", "app", "generated", "docs.ts");
const defaultDocumentPath = path.join(root, "docs-site", "app", "generated", "default-doc.ts");
const publicDataRoot = path.join(root, "docs-site", "public", "docs-data");

const categoryLabels = {
  guides: { en: "Guides", zh: "指南" },
  product: { en: "Product & API", zh: "产品与 API" },
  architecture: { en: "Architecture", zh: "架构决策" },
  operations: { en: "Operations", zh: "运维手册" },
  delivery: { en: "Delivery evidence", zh: "交付记录" },
  policy: { en: "Policy & store", zh: "政策与商店" },
};

const files = (await walk(sourceRoot))
  .filter((file) => file.endsWith(".md") || file.endsWith(".json"))
  .sort((a, b) => orderFor(a) - orderFor(b) || a.localeCompare(b));
const publishedPaths = new Set(
  files.map((file) => path.relative(sourceRoot, file).split(path.sep).join("/")),
);

const docs = [];
const contents = [];
await mkdir(publicDataRoot, { recursive: true });
for (const sourcePath of files) {
  const relativePath = path.relative(sourceRoot, sourcePath).split(path.sep).join("/");
  const id = relativePath.replace(/\.(?:md|json)$/i, "").replaceAll("/", "--");
  const isJson = sourcePath.endsWith(".json");
  const source = await readFile(sourcePath, "utf8");
  const translatedPath = path.join(translatedRoot, relativePath);
  const translatedDraft = isJson ? source : await readFile(translatedPath, "utf8").catch(() => source);
  const translated = isJson ? source : normalizeTechnicalNumbers(source, translatedDraft);
  const html = isJson ? renderJson(source) : renderMarkdown(source, relativePath);
  const htmlZh = isJson ? html : renderMarkdown(translated, relativePath);
  const title = isJson ? "OpenAPI v1 contract" : extractTitle(source, relativePath);
  const titleZh = isJson ? "OpenAPI v1 接口契约" : extractTitle(translated, relativePath);
  const summary = isJson
    ? "The generated machine-readable contract for the Pakperk v1 HTTP API."
    : extractSummary(source);
  const summaryZh = isJson
    ? "Pakperk v1 HTTP API 的机器可读生成契约。"
    : extractSummary(translated);
  const category = categoryFor(relativePath);

  docs.push({
    id,
    path: relativePath,
    category,
    categoryLabel: categoryLabels[category],
    title,
    titleZh,
    summary,
    summaryZh,
    dataUrl: `/docs-data/${id}.json`,
    wordCount: source.trim().split(/\s+/).length,
    readingMinutes: Math.max(1, Math.ceil(source.trim().split(/\s+/).length / 230)),
    toc: extractToc(html),
    tocZh: extractToc(htmlZh),
  });
  const content = { id, html, htmlZh };
  contents.push(content);
  await writeFile(path.join(publicDataRoot, `${id}.json`), JSON.stringify(content), "utf8");
}

await mkdir(path.dirname(generatedPath), { recursive: true });
await writeFile(
  generatedPath,
  `// Generated by scripts/generate-docs.mjs. Do not edit by hand.\n` +
    `export const docs = ${JSON.stringify(docs)} as const;\n`,
  "utf8",
);
const defaultDocument = contents.find((document) => document.id === "developer-guide") || contents[0];
await writeFile(
  defaultDocumentPath,
  `// Generated by scripts/generate-docs.mjs. Do not edit by hand.\n` +
    `export const defaultDocument = ${JSON.stringify(defaultDocument)} as const;\n`,
  "utf8",
);
console.log(`Generated ${docs.length} bilingual documents at ${generatedPath}`);

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(entryPath)));
    else files.push(entryPath);
  }
  return files;
}

function renderMarkdown(markdown, relativePath) {
  const rendered = execFileSync(
    "pandoc",
    ["--from=gfm", "--to=html5", "--wrap=none", "--shift-heading-level-by=1"],
    { input: markdown, encoding: "utf8", maxBuffer: 16 * 1024 * 1024 },
  );
  return rewriteLinks(rendered, relativePath);
}

function renderJson(source) {
  return `<pre><code class="language-json">${escapeHtml(source)}</code></pre>`;
}

function rewriteLinks(html, relativePath) {
  return html.replace(/href="([^"]+)"/g, (match, href) => {
    if (/^(?:[a-z]+:|#|\/)/i.test(href)) return match;
    const [target, anchor = ""] = href.split("#", 2);
    const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(relativePath), target));
    if (publishedPaths.has(resolved)) {
      const id = resolved.replace(/\.(?:md|json)$/i, "").replaceAll("/", "--");
      return `href="/?doc=${encodeURIComponent(id)}${anchor ? `&section=${encodeURIComponent(anchor)}` : ""}" data-doc-link="${id}"${anchor ? ` data-doc-section="${escapeHtml(anchor)}"` : ""}`;
    }
    if (resolved.startsWith("../")) {
      const repositoryPath = resolved.replace(/^(?:\.\.\/)+/, "");
      const view = target.endsWith("/") ? "tree" : "blob";
      return `href="https://github.com/ErrDivine/PakPerk/${view}/main/${escapeHtml(repositoryPath)}${anchor ? `#${escapeHtml(anchor)}` : ""}" target="_blank" rel="noreferrer"`;
    }
    if (target.endsWith("/") || /\.[a-z0-9]+$/i.test(target)) {
      const view = target.endsWith("/") ? "tree" : "blob";
      return `href="https://github.com/ErrDivine/PakPerk/${view}/main/docs/${escapeHtml(resolved)}${anchor ? `#${escapeHtml(anchor)}` : ""}" target="_blank" rel="noreferrer"`;
    }
    return match;
  });
}

function extractTitle(source, relativePath) {
  return source.match(/^#\s+(.+)$/m)?.[1]?.replace(/[`*_]/g, "") || humanize(relativePath);
}

function extractSummary(source) {
  const paragraph = source
    .split(/\n\s*\n/)
    .map((part) => part.trim())
    .find((part) => part && !/^(?:#|```|[-*+]\s|\d+\.\s|\|)/.test(part));
  const clean = stripMarkdown(paragraph || "").replace(/\s+/g, " ").trim();
  return clean.length > 220 ? `${clean.slice(0, 217).trimEnd()}…` : clean;
}

function stripMarkdown(source) {
  return source
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/^\s*(?:[-*+]|\d+\.)\s+/gm, "")
    .replace(/[>*_|]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function extractToc(html) {
  return [...html.matchAll(/<h([23]) id="([^"]+)">([\s\S]*?)<\/h\1>/g)].map((match) => ({
    level: Number(match[1]),
    id: match[2],
    label: match[3].replace(/<[^>]+>/g, "").replaceAll("&amp;", "&"),
  }));
}

function categoryFor(relativePath) {
  if (/^(?:user-guide|developer-guide|mobile-app-links)\.md$/.test(relativePath)) return "guides";
  if (relativePath.startsWith("adr/") || relativePath === "architecture.md") return "architecture";
  if (relativePath.startsWith("runbooks/")) return "operations";
  if (relativePath.startsWith("phase-reports/") || /(?:completion-audit|production-v0\.0-plan|mobile-release)/.test(relativePath)) return "delivery";
  if (relativePath.startsWith("legal/") || relativePath.startsWith("store/") || relativePath === "content-policy.md") return "policy";
  return "product";
}

function orderFor(file) {
  const relativePath = path.relative(sourceRoot, file).split(path.sep).join("/");
  const category = categoryFor(relativePath);
  const categoryOrder = ["guides", "product", "architecture", "operations", "delivery", "policy"];
  const featured = ["user-guide.md", "developer-guide.md", "architecture.md", "openapi-v1.json"];
  const featuredIndex = featured.indexOf(relativePath);
  return categoryOrder.indexOf(category) * 1_000 + (featuredIndex >= 0 ? featuredIndex : 100);
}

function humanize(value) {
  return value
    .replace(/\.(?:md|json)$/i, "")
    .split("/")
    .at(-1)
    .replaceAll("-", " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function escapeHtml(value) {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function normalizeTechnicalNumbers(source, translation) {
  const pattern = /\d[\d.,:%/+_-]*/g;
  const originals = source.match(pattern) || [];
  const translatedValues = translation.match(pattern) || [];
  if (originals.length !== translatedValues.length) return translation;
  let index = 0;
  return translation.replace(pattern, () => originals[index++]);
}
